[package]
name = "batch_client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
tokio = { version = "1", features = ["full"] }
ndarray = "0.15"
ndarray-npy = "0.8"
qdrant-client = { path = "../vendor/qdrant-client", default-features = false, features = ["serde"] }
csv = "1.4.0"
chrono = "0.4.42"
serde_json = "1"
