#!/usr/bin/env python3
"""Generate docs/config-reference.md from schema definitions."""

from __future__ import annotations

import shlex
from dataclasses import dataclass
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = REPO_ROOT / "docs" / "config-reference.md"


@dataclass(frozen=True)
class SchemaVar:
    name: str
    requirement: str
    default: str
    choices: str
    description: str
    required_if: str


SCHEMAS = [
    {
        "title": "Shared Parameters",
        "source_label": "common/schema.sh",
        "source_path": REPO_ROOT / "common" / "schema.sh",
        "register_fn": "register_common_var",
        "notes": [
            "These variables apply across all engines.",
            "Some variables are only conditionally required based on `TASK` or `RUN_MODE`.",
            "Sweep values are space-separated lists in env-style config files.",
        ],
    },
    {
        "title": "Qdrant Parameters",
        "source_label": "qdrant/schema.sh",
        "source_path": REPO_ROOT / "qdrant" / "schema.sh",
        "register_fn": "register_qdrant_var",
        "notes": [
            "Qdrant-specific behavior may derive additional runtime values from other settings.",
        ],
    },
    {
        "title": "Milvus Parameters",
        "source_label": "milvus/schema.sh",
        "source_path": REPO_ROOT / "milvus" / "schema.sh",
        "register_fn": "register_milvus_var",
        "notes": [
            "Milvus-specific runtime behavior may derive storage and topology details automatically.",
        ],
    },
    {
        "title": "Weaviate Parameters",
        "source_label": "weaviate/schema.sh",
        "source_path": REPO_ROOT / "weaviate" / "schema.sh",
        "register_fn": "register_weaviate_var",
        "notes": [
            "Weaviate collection creation also depends on `weaviate/scripts/create_basic_collection.py`.",
            "When unset, `HNSW_DYNAMIC_THRESHOLD` may be derived from `INSERT_CORPUS_SIZE` or `INSERT_DATA_FILEPATH`.",
        ],
    },
]


def parse_schema(schema_path: Path, register_fn: str) -> list[SchemaVar]:
    vars_: list[SchemaVar] = []
    for raw_line in schema_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line.startswith(register_fn):
            continue
        tokens = shlex.split(line, comments=False, posix=True)
        if len(tokens) < 6:
            raise ValueError(f"Could not parse schema line in {schema_path}: {raw_line}")
        args = tokens[1:]
        while len(args) < 6:
            args.append("")
        if len(args) == 6:
            args.append("")
        vars_.append(
            SchemaVar(
                name=args[0],
                requirement=args[1],
                default=args[2],
                choices=args[3],
                description=args[4],
                required_if=args[5],
            )
        )
    return vars_


def format_requirement(var: SchemaVar) -> str:
    if var.requirement == "required":
        return "required"
    if var.requirement == "conditional":
        if var.required_if:
            return f"required when `{var.required_if}`"
        return "conditional"
    if var.default:
        return f"`{var.default}`"
    return "optional"


def format_choices(var: SchemaVar) -> str:
    if not var.choices:
        return "free-form"
    parts = var.choices.split()
    return ", ".join(f"`{part}`" for part in parts)


def format_notes(var: SchemaVar) -> str:
    notes = [var.description]
    if var.required_if and var.requirement != "conditional":
        notes.append(f"Condition: `{var.required_if}`")
    return " ".join(notes)


def format_source_link(label: str) -> str:
    return f"[{label}](../{label})"


def render_section(section: dict[str, object]) -> str:
    vars_ = parse_schema(section["source_path"], section["register_fn"])  # type: ignore[index]
    title = section["title"]  # type: ignore[index]
    source_label = section["source_label"]  # type: ignore[index]
    notes = section["notes"]  # type: ignore[index]

    lines = [f"## {title}", "", "Source of truth:", "", f"- {format_source_link(source_label)}", ""]
    lines.extend(f"- {note}" for note in notes)
    lines.extend(
        [
            "",
            "| Name | Default / Requirement | Choices | Notes |",
            "|---|---|---|---|",
        ]
    )
    for var in vars_:
        lines.append(
            f"| `{var.name}` | {format_requirement(var)} | {format_choices(var)} | {format_notes(var)} |"
        )
    lines.append("")
    return "\n".join(lines)


def render_document() -> str:
    lines = [
        "# Config Reference",
        "",
        "<!-- Generated by docs/generate_config_reference.py. Edit schema files instead of this document. -->",
        "",
        "This document is generated from the schema definitions. The schema files remain the",
        "source of truth.",
        "",
    ]
    for section in SCHEMAS:
        lines.append(render_section(section))
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    OUTPUT_PATH.write_text(render_document(), encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
